### ISSUE TITLE
Not working with new tv3play.se or viafree.se

### ISSUE THREAD

**Issue by tooobe** [bubach/AdfreePlay#2]
Hi, the plugin is not working with new tv3play.se or viafree.se 
Any work being done on this plugin still or is it dead? :)

**Comment by bubach** [comment]
I haven't been using it myself for quite some time - and as such haven't had time to check any changes made to the streaming sites.  Anybody with some spare time to spend in chrome developer tools sniffing http-request can send me a pull request for changes.

**Comment by bubach** [comment]
Now added viafree support
